Type: AWS::Serverless::StateMachine
Properties:
  Name: approve-leave
  DefinitionUri: stepfunction/approve-leave.asl.json
  DefinitionSubstitutions:
    ApproveLeaveArn:
      Fn::GetAtt:
        - ApproveLeave
        - Arn
    WaitForTaskTokenArn:
      Fn::GetAtt:
        - WaitForTaskToken
        - Arn
  Policies:
    - CloudWatchLogsFullAccess
    - LambdaInvokePolicy:
        Effect: Allow
        Action: lambda:InvokeFunction
        FunctionName: '*'
        Resource:
          - Fn::GetAtt:
              - WaitForTaskToken
              - Arn
          - Fn::GetAtt:
              - ApproveLeave
              - Arn
  Logging:
    IncludeExecutionData: true
    Level: ALL
    Destinations:
      - CloudWatchLogsLogGroup:
          LogGroupArn:
            Fn::GetAtt:
              - LeaveApplicationLogGroup
              - Arn
  Events:
    Root:
      Type: Api
      Properties:
        RestApiId:
          Ref: LeaveApprovalApi2
        Path: /requestLeave
        Method: POST
