AWSTemplateFormatVersion: '2010-09-09'
Description: sam-app
Transform:
  - AWS::Serverless-2016-10-31
Resources:
  ApiGatewayApi: ${file:infra_resources/Resources/ApiGatewayApi.yaml}
  getAllItemsFunction: ${file:infra_resources/Resources/getAllItemsFunction.yaml}
  getByIdFunction: ${file:infra_resources/Resources/getByIdFunction.yaml}
  putItemFunction: ${file:infra_resources/Resources/putItemFunction.yaml}
  SampleTable: ${file:infra_resources/Resources/SampleTable.yaml}
  CloudFrontDistribution: ${file:infra_resources/Resources/CloudFrontDistribution.yaml}
  CloudFrontOriginAccessControl: ${file:infra_resources/Resources/CloudFrontOriginAccessControl.yaml}
  WebSiteBucket: ${file:infra_resources/Resources/WebSiteBucket.yaml:bucket}
  WebSiteBucketPolicy: ${file:infra_resources/Resources/WebSiteBucket.yaml:bucketPolicy}
  WebSiteBucket2: ${file:infra_resources/Resources/WebSiteBucket2.yaml}
  WebSiteBucket3bucketPolicy: ${file:infra_resources/Resources/WebSiteBucket3.yaml:bucketPolicy}
  ApiGatewayApi2: ${file:infra_resources/Resources/ApiGatewayApi1.yaml:2}
  ApiGatewayApi3: ${file:infra_resources/Resources/ApiGatewayApi1.yaml:3}
  testtempale: ${file:infra_resources/Resources/testtempale.yaml}
Outputs: ${file:infra_resources/Outputs.yaml}
