'2':
  Type: AWS::Serverless::Api
  Properties:
    StageName: Prod
    Cors:
      AllowMethods: '''OPTIONS, POST, GET'''
      AllowHeaders: '''Content-Type'''
      AllowOrigin: '''*'''
'3':
  Type: AWS::Serverless::Api
  Properties:
    StageName: Prod
    Cors:
      AllowMethods: '''OPTIONS, POST, GET'''
      AllowHeaders: '''Content-Type'''
      AllowOrigin: '''*'''
